### ISSUE TITLE
Vimeo: embed reversal fails with some vimeo URL formats

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10529]
#### Steps to reproduce the issue

1. Make sure Jetpack's Shortcodes module is enabled on your site.
2. Go to Posts > Add New and create a new post including the 3 following URLs, on separate lines:
```html
https://vimeo.com/289091934/cd1f466bcc
https://vimeo.com/album/2838732/video/6342264
https://vimeo.com/6342264
```

All 3 URL formats do work and return an embed in the post editor, since they are valid URL formats and Core's oEmbed method handles them. However, on the frontend of your site only the third video will work: the 2 first ones will only return the following error:

`<!-- vimeo error: not a vimeo video -->`

We would need to update our embed reversal method to support those URLs as well.

**Comment by kraftbj** [comment]
As mentioned in Slack, if Core handles all of the cases we're currently handling, we probably should just look to not override oEmbed. We can keep any iframe->shortcode or iframe->URL conversions though.

**Comment by jeherve** [comment]
> if Core handles all of the cases we're currently handling, we probably should just look to not override oEmbed. 

As far as I can tell they do, and they also handle the cases above.

**Comment by kraftbj** [comment]
Kicked off a PR for the sake of testing. I would generally trust Core's long-term maintainability of oEmbed's that they support, so want to try first just removing our handler.

**Comment by JoshuaGoode** [comment]
Encountered today on a WPCOM site with hosting features enabled. 

Video shows in editor but you get `<!-- vimeo error: not a vimeo video -->` on the front-end.

Had to use a different URL such as https://player.vimeo.com/video/xxxxxx and/or the iframe code to resolve.

**Comment by druesome** [comment]
Another issue on an AT site.

Pasting a Vimeo URL into the block editor would automatically convert into a Vimeo block, but video won't show up on the front end unless the Shortcodes module is turned off. Pasting in the `https://player.vimeo.com/video/xxxxxx` format works in all cases, though, but has to be placed in an HTML block to show up.

**Comment by donalirl** [comment]
Just reminding myself to update the support doc if this gets fixed 

https://github.com/Automattic/en.support-docs-content/issues/573

**Comment by druesome** [comment]
Got another case on an AT site.  Their private showcase only showed up in the front end when the shortcodes module was turned off.

**Comment by oyadeyiseun** [comment]
Noticed this on another site today, 25275714-HC
Vimeo URL: https://vimeo.com/466336705/59eb8d81e3

**Comment by xpurichan** [comment]
Experienced in 12441064-hc

**Comment by bsanevans** [comment]
Got another case of this here: 26070978-hc

Replacing the link structure with `https://player.vimeo.com/video/xxxxxx` worked.

**Comment by Greatdane** [comment]
Had another case of this here; 31463133-hc
Follow up here; 4287210-zd-woothemes

Replacing the link structure with `https://player.vimeo.com/video/xxxxxx` also worked.

**Comment by JoshuaGoode** [comment]
Encountered on 32528438-hc

User attempted to embed https://vimeo.com/470165945/df204ef0ec

As a workaround, deactivated Shortcode module for now.

**Comment by edequalsawesome** [comment]
Also reported in 33102724-hc, will let the customer know to use the HTML block to embed the video.

**Comment by sharonlaker19** [comment]
+1 at 4626490-zen
Deactivating the shortcode module worked.

**Comment by jeherve** [comment]
closing this again, since the problem is fixed in the development version of the plugin. The fix will ship wit the next Jetpack release.

**Comment by JoshuaGoode** [comment]
@ash1eygrace  Encountered again on a WPCOM Atomic hosted site today.  Toggling off the `shortcodes` module was necessary to get the video to work.

### Example
Page was using an embed block.

The video URL inserted followed this format:

https://vimeo.com/XXXXXXXXX and the editor successfully displayed a working preview of the video.

```
<!-- wp:embed {"url":"https://vimeo.com/XXXXXXXXX","type":"video","providerNameSlug":"vimeo","responsive":true,"className":"wp-embed-aspect-16-9 wp-has-aspect-ratio"} -->
<figure class="wp-block-embed is-type-video is-provider-vimeo wp-block-embed-vimeo wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://vimeo.com/XXXXXXXXX
</div></figure>
<!-- /wp:embed -->
```

The editor pulled in `https://player.vimeo.com/video/XXXXXXXXX?h=xxxxxxxxxx&dnt=x&app_id=xxxxxx` for the embed block's preview.

##### Frontend

On the frontend, the page attempts to load `https://player.vimeo.com/video/XXXXXXXXX` which 404 and displays the following.

> Sorry
This video does not exist.

![Screen Shot on 2022-01-26 at 17:05:13](https://user-images.githubusercontent.com/4887830/151254845-ee46898a-0c9c-4b0b-b2fc-61d62e70a5c3.png)

#### Workaround

Deactivate off the `shortcodes` Jetpack module.

Internal discussion: p1643233702053900/1643232361.051700-slack-C02E26A26CT

**Comment by jeherve** [comment]
@JoshuaGoode I can't seem to be able to reproduce the issue at the moment. The video in your example seems to be private, and I cannot embed it, whether I use Jetpack or not. Here is how it looks like when I do not use Jetpack:
<img width="821" alt="Screenshot 2022-01-28 at 18 06 55" src="https://user-images.githubusercontent.com/426388/151590793-0894f921-0153-4146-b3f8-f5fed1624f55.png">
 
Was the video public yesterday? Any chance you can still reproduce the problem today?

**Comment by JoshuaGoode** [comment]
@jeherve Looking closer, the videos from the recent report utilize domain restrictions on Vimeo's end so they can only be embedded on sites with designated domains. 

* https://vimeo.zendesk.com/hc/en-us/articles/224817847-Manage-your-video-s-privacy-settings/#h_01FK121RSVV5YAB2G1A4WKKJM0

The issue still occurs if we enable the `shortcodes` module.

**Comment by jeherve** [comment]
That makes sense now, thanks for the extra details. It seems like we'll need to add a Referer header to such requests, as per Vimeo documentation:
https://developer.vimeo.com/api/oembed/videos
> To get the complete response, including the private metadata, send the Referer header with the request, and set its value to the video's whitelisted domain.

**Comment by cuemarie** [comment]
Not sure if this is the same, but I ran into a **simple site** today having issues embedding Vimeo as well, here: 138349-hc

**What Didn't Work**

- Embedding the link in `https://vimeo.com/XXXXXXXXX` format resulted in just the link code displaying on the front end.

**What Did Work**

- Displaying the video using shortcode `[vimeo XXXXXXXX]`
- Embedding the video using `https://player.vimeo.com/video/xxxxxx` format 
- Using the Vimeo's Embed Code in a Custom HTML Block

**Comment by zdenys** [comment]
4886160-zd-woothemes. I suggested one of the workarounds from [the above comment](https://github.com/Automattic/jetpack/issues/10529#issuecomment-1058228312).

**Comment by aleone89** [comment]
Another report here: https://wordpress.com/forums/topic/problem-z-osadzaniem-video-z-vimeo/ 

- Simple site 
- This happened in FSE > index template 
- Switching index to the posts page in the customizer did not solve the issue 
- Embedding the video using https://player.vimeo.com/video/xxxxxx format also did not work
- Embedding via shortcode and HTML did work
