### ISSUE TITLE
Sync: Callables: Allow shutdown sync on CLI commands

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/jetpack#12924]
#### Steps to reproduce the issue

1. Run `wp option update home https://some-new-domain.com`
2. Check the `home` option on WP.com / Jetpack side - it's unchanged
3. "Manually" sync callables (such as via the JP Debug tool)
4. `home` is now correct on WP.com / Jetpack side

#### What I expected

Like other content changes that are synced on shutdown, changing options that are handled via "functions/callables" should also cause a sync on shutdown.

#### What happened instead

The new value was not synced until a sync was manually triggered.

This is because of the conditional here:

https://github.com/Automattic/jetpack/blob/40e18f0e223e4f7f86c620a1cde506ff6e194d71/packages/sync/src/modules/Callables.php#L219

Related - it also bails on Cron, which doesn't seem great, because then callables are only synced on admin requests - is that still desired?

cc @Automattic/poseidon

**Comment by gititon** [comment]
Hi @nickdaugherty,

I wanted to let you know that I've been working on [this issue](https://github.com/Automattic/jetpack/pull/13015). At this point it's a matter of getting all of the tests passing, which I hope to finish tomorrow.

**Comment by tyxla** [comment]
Hey @nickdaugherty we've also got the tests to pass, so the PR is also in a testable state right now.

We'd appreciate your help in testing/reviewing the PR in order to ship it and resolve the issue as soon as possible.

**Comment by gititon** [comment]
@nickdaugherty https://github.com/Automattic/jetpack/pull/13015 has been merged, so this should work now.

**Comment by nickdaugherty** [comment]
Thanks @gititon, much appreciated!

**Comment by nickdaugherty** [comment]
Hey @gititon, I did some testing and I don't think it's _quite_ fixed. The changes come through eventually (I'm guessing through cron), but not in direct response to the CLI command itself, it seems.

I left a note on the PR, I think we're still not properly doing the sync on shutdown for CLI commands, b/c it aborts if the request isn't Cron (which WP CLI is not).

**Comment by gititon** [comment]
Hi @nickdaugherty , can you please try again on master and confirm whether the latest changes do the trick? Thanks!

**Comment by nickdaugherty** [comment]
Hey @gititon, I just retested on fresh build of master, and there are 2 things not working right for me:

The `home` option syncs correctly and instantly the first 2 times I run it. However, it then stops syncing once the `jetpack_sync_callables_await` transient exists (which I guess is by design?). The problem is, if a site has that lock for something else, then you run `wp option update home https://my-new-domain.com`, the new value doesn't get synced, so the syncing is unreliable.

The other problem is that `siteurl` doesn't seem to be updating at all. I think that's because we also need to map `siteurl` => `site_url` in this mapping (?):

https://github.com/Automattic/jetpack/blob/3d9e58d01227e37e2d3056fb2ea2b4d6d68e5f42/packages/sync/src/modules/Callables.php#L66

`wp option update siteurl https://my-new-domain.com` doesn't sync the new value up.

**Comment by gititon** [comment]
Thanks for your feedback, @nickdaugherty. I'll prepare another patch in the morning to address site_url and give the wait time some thought. For context, can you please tell me why we need these options to bypass normal sync constraints and always sync immediately?

**Comment by gititon** [comment]
Hi @nickdaugherty,

I have a pull request in that will let siteurl sync as well, and ensures that both siteurl and home sync instantly when changed via WP CLI, https://github.com/Automattic/jetpack/pull/13132.

**Comment by gititon** [comment]
Hi @nickdaugherty, https://github.com/Automattic/jetpack/pull/13132 has been merged, so you should have the additional functionality you were looking for now.

**Comment by nickdaugherty** [comment]
Awesome, I'll try it out as soon as I can. To answer you question, the use case is launching a new site - site has a "placeholder" domain up until the point of DNS switching, then DNS is flipped and the home/siteurls are updated back to back...so it'll start receiving traffic and it's important the cache site is in sync. Technically a delay of a minute or two may be ok, but IMO better to do it straight away.

**Comment by gititon** [comment]
Roger that, thanks for filling me in, @nickdaugherty. Please let me know how it works for you when you have a chance.

**Comment by jeherve** [comment]
Closing this for now since #13132 has been merged. @nickdaugherty Feel free to reopen if there are still issues in your testing.

**Comment by nickdaugherty** [comment]
Awesome, tested it out and it seems much better. Changing the home/siteurl several times in a row occasionally ended up with out-of-date data on the cache site, but it does seem much more reliable (and `siteurl` now syncs). Thanks for working on this!
