### ISSUE TITLE
Tiled gallery block: Switching from other blocks to Tiled Galleries does not load

### ISSUE THREAD

**Issue by edwinho89** [Automattic/jetpack#13254]
#### Steps to reproduce
1. Create a new post, add a new gallery block, and include a couple of images.
2. From the gallery block, switch to tiled gallery block
3. Click on any area outside of tiled gallery block
4. Click back on any images within the tiled gallery block

#### What I expected
By switching to tiled gallery block, the images loads normally

#### What happened instead
After switching to tiled gallery block, the block appeared blank instead

![image link 1](https://cldup.com/KrGAxMhMqQ.png)
image link: https://cloudup.com/cAvugxj5I70

#### Screenshot / Video

video link: https://cloudup.com/c4--aHEWtvJ

#### Context / Source

A similar issue was reported in https://github.com/Automattic/wp-calypso/issues/29766 , however there aren't any error messages appearing on console.

Reported on 2264152-zen

**Comment by simison** [comment]
Thanks for the report! Moved to Jetpack repo where the code also is.

**Comment by tijosh** [comment]
Noting that due to https://github.com/Automattic/wp-calypso/issues/36406 we are seeing an uptick in this issue affecting WPcom users who are switching to Tiled Gallery as a workaround.

**Comment by katinthehatsite** [comment]
Another request in 2396577-zen

**Comment by tijosh** [comment]
I've noticed that clicking into the empty gray boxes when switching helps populate all the needed information to make the gallery work correctly.

**Comment by rinazrina** [comment]
Another report: 16983577-hc

**Comment by automattic-ian** [comment]
Seems this is related: https://github.com/Automattic/wp-calypso/issues/39144

**Comment by lizswafford** [comment]
Reported in - 2656593-zen

**Comment by pauljacobson** [comment]
I tested @tijosh's suggestion, and it works. Take a look [here](https://d.pr/i/GJCtoe/Iils6MveAc).

**Comment by jeherve** [comment]
This should be fixed as of #20583.

**Comment by Nic-Sevic** [comment]
Hi! I have another instance of this here: 4264990-zd-woothemes

I also tested on both AT and simple sites with different themes. On AT when the gallery converts the images show grey in editor but appear when you click a grey square with nothing showing in preview or live. On simple the images show immediately but still not on preview/live.

Once converted the code for it looks like this (top is the converted gallery bottom is the one inserted as a tiled gallery originally):
![2021-09-01 at 17 08](https://user-images.githubusercontent.com/47717887/131686318-00fff059-8a84-4ffd-ad1c-eb25d4a9e847.jpg)

or this for the simple site: 
![2021-09-01 at 17 09](https://user-images.githubusercontent.com/47717887/131686535-963af9d6-d7e0-4d2c-9379-cc2d11bd8ae1.jpg)

**Comment by sdixon194** [comment]
Thanks @Nic-Sevic - thanks for reporting again. It does indeed look like transforming from Gallery -> Tiled Gallery doesn't work on the live site, just the editor. Or rather, transforming from any block to the tiled gallery doesn't work on the live site. Transforming from tiled gallery -> gallery/other blocks works fine. (note that this fix is only available on wpcom sites as of now - Atomic and Jetpack releases won't happen until next week).

CC @glendaviesnz

**Comment by sdixon194** [comment]
Interestingly, I can only reproduce on JN or live sites - my local and Jurassic Tube sites don't have this issue.

It seems there's an issue with updating. When transforming from gallery -> tiled gallery, if I click "update" and then make another change on the page that lets me click the update button again (such as adding text to another block, or even just clicking on one of the gallery images), the tiled gallery works on the live site again.

**Comment by glendaviesnz** [comment]
@sdixon194 I was able to replicate this, on relooking at it the previous fix wasn't the right approach 🤦 - a more robust fix (hopefully) is up at https://github.com/Automattic/jetpack/pull/20928
