### ISSUE TITLE
Search: results with shortcodes should get expanded

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15426]
We need to expand shortcodes or remove them from the search results

![Screen Shot on 2020-04-08 at 19-36-04](https://user-images.githubusercontent.com/820871/79136647-94877000-7d6e-11ea-946b-7bd65742baa5.png)

**Comment by jeremypaavola** [comment]
Reported in 2960664-zen

**Comment by gibrown** [comment]
Bulk indexing is still running (should be done tomorrow), but this should now be fixed for all sites.

**Comment by aicee** [comment]
Hi @gibrown ! Could you kindly take a look at this ticket: https://woothemes.zendesk.com/agent/tickets/2960664

Site: https://enolight.com
Jetpack Debugger: https://jetpack.com/support/debug/?url=160507034
JP version is 8.5.

User is still seeing shortcodes on search results here: https://enolight.com/?s=viv
![](https://cdn-std.droplr.net/files/acc_876247/JIyyDm)
Image Link: https://d.pr/i/JIyyDm

Thank you!

**Comment by gibrown** [comment]
@aicee that site is all fixed now, and I am bulk reindexing all other sites to remove any other sites using ElegantThemes Pagebuilder shortcodes. Going to close this since we now have an easy way to remove shortcodes like this.

**Comment by gaurav1984** [comment]
Hi @gibrown _ElegantThemes Pagebuilder shortcodes_ issue has been fixed for https://enolight.com but now they are seeing a new issue.

On this page https://enolight.com/?s=viv
Here is what they are seeing now


![](https://p20.zdusercontent.com/attachment/215490/jpj3F1vjxbnlYxWn3QsoSPT3O?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..rop5ZGFRXrJBjZCut81-qg.Sdo_U_1rgHsbTKtYlN2nlIBvxCV0iNXkEUbVX18_EvG5SqMbE4CCwmeAIW-So7Q_qKUsHRxT3CBBkRY9SfNK7yvzF1Lba3YRjxE012AybJXsFEdJs3m_GBosdnmkqvTdHscNYylfl7Q2Q8axEHSNxX2CCWAtOgpej7mkk-UTo42Z3AcC3PuQHHl4iAfglwnEY4A4-U9-hdJpuKaL3K4MsfibJc5lUpmwAw_tDOtJn7cz60y_EFqB2uN1evaTOnVP4xfut6YbsrWuTFyWO1PWRTm3fSOnFzwelwgEEvQXrtg.b2I3MFBo0De7__GAOCGGQQ)

Can you please have a look :)
