### ISSUE TITLE
 Classic Editor adds extra p tags to Instagram Embed 

### ISSUE THREAD

**Issue by hitolonen** [Automattic/jetpack#17329]
#### Steps to reproduce the issue

1. Use Classic Editor.
2. Place Instagram post url to editor (doesn't matter Visual, Text, with or without p tags)
3. Save Post.
4. Check frontend code. 

#### What I expected
No extra p tags, eg what you get with `remove_filter( 'the_content', 'wpautop' );`.

#### What happened instead

Closing `</p>` tag after the first link: 

```
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-permalink="xxx" data-instgrm-version="12" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:640px; min-width:326px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);">
<div style="padding:16px;"> <a href="xxx" style=" background:#FFFFFF; line-height:0; padding:0 0; text-align:center; text-decoration:none; width:100%;" target="_blank"> </p>
```
Closing `</a>` is inside p tag: `<p></a> </p>`

#### Other information

This is essentially the same issue as https://core.trac.wordpress.org/ticket/51328 - it only happens with Classic Editor, with and without Jetpack. Core probably won't fix as they are removing the Instagram embed?

**Comment by hitolonen** [comment]
@jeherve am I testing correctly and this has been fixed in Jetpack 9.0 thanks to https://github.com/Automattic/jetpack/pull/17192? 

My testing workflow for Insta embeds prior to Jetpack 9.0:

- When using Core embeds, Insta embed have the extra p tags and also `//www.instagram.com/embed.js` (check source code).
- When upgraded to Jetpack 9.0-beta and setting "Write posts or pages in plain-text Markdown syntax" is enabled, `//www.instagram.com/embed.js` is removed (embeds use Jetpack). When the setting is disabled, the file is back (embeds back to using Core).
- When upgraded to Jetpack 9.0, Jetpack takes over and the whole html block is now different and no extra p tags nor `//www.instagram.com/embed.js`.

**Comment by jeherve** [comment]
This was still happening in the classic block in my last test, but I haven't tested in the past few days. If you cannot reproduce anymore, feel free to close!

**Comment by hitolonen** [comment]
Ah, you are right! Sorry about the confusion :) It's only the file `//www.instagram.com/embed.js` that's been removed, but the extra p tags do remain.

**Comment by janvitos** [comment]
I can confirm the bug still exists in WordPress 6.2.2.

This bug is also breaking W3C Feed Validation and is preventing Google Publisher from updating my feed through WebSub because of the "Invalid HTML" error.

`[line 320](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.example.com%2Ffeed%2F#l320), column 0: Invalid HTML: Unexpected end tag (p). Ignored.`

`Check the feed using the [RSS validator](https://validator.w3.org/feed) and make sure it validates and does not contain any 'invalid html' errors. If it doesn't validate, or has 'invalid html', it won't be processed for your Publication. This is the first thing to check when you are having problems.`

https://support.google.com/news/publisher-center/thread/201695889?hl=en&sjid=7931435817889299683-NA

When disabling wpautop, the extra <\/p> tag and "Invalid HTML" error disappear.

- I am using the Classic Editor.
- I need wpautop because my website has over 6,000 articles without actual p tags in the editor, so I cannot simply disable it as I will loose the p tags.

@hitolonen, have you found a temporary fix for this? How have you been working around this issue since 2020?

**Comment by raicem** [comment]
We're also experiencing this issue with GitHub Gists. When Jetpack handles embeds for Gists, we end up with empty `p` tags in the content, and the layout is broken. We believe this is because WordPress running `wpautop` so it's only happening in posts that only consist of the classic block.

![image](https://github.com/Automattic/jetpack/assets/10389957/2c86c6ff-cb2b-4ffe-bb51-5fc9e7db6768)

To reproduce:
1) Start a fresh WordPress site (I used j[urassic.ninja](https://jurassic.ninja/) just for testing)
2) Activate Jetpack and go to **Jetpack > Settings > Writing** to enable **Compose using shortcodes to embed media from popular sites**
3) Create a new post and insert a classic block
4) Insert any gist URL into the classic block and publish the post
5) View the post and see the malformed layout

The workaround is to add one empty paragraph block after the classic block. Then [WordPress stops running](https://github.com/WordPress/WordPress/blob/29c16a48ec21427ba5299fb4c2d7c4749ae3337b/wp-includes/class-wp-editor.php#L88) `wpautop` and there is no extra empty `p` tags. Maybe this workaround can work for you here @janvitos.

**Comment by janvitos** [comment]
I just want to clarify a few things regarding my WordPress setup.

- I am using the Classic Editor
- I need wpautop because my website has over 6,000 articles without actual p tags in the editor, so I cannot simply disable it.
- I've tried copying the wpautop function and modifying it by removing div and blockquote tags from the $allblocks variable, and although it does seem to have less of an impact on the Instagram embed code, it doesn't fix the problem. I suspect other regex are causing the issue.

**Comment by janvitos** [comment]
So, after spending more time on this issue, I decided to modify the wpautop function to suit my needs. I removed most of the code and kept only the newline and paragraph parts, and made sure to omit any html tags since I only want p tags around text.

This is what I ended up with:

```
function wpautop_custom( $text ) {
    $pre_tags = array();

    if ( trim( $text ) === '' ) {
        return '';
    }

    // Just to make things a little easier, pad the end.
    $text = $text . "\n";

    // Standardize newline characters to "\n".
    $text = str_replace( array( "\r\n", "\r" ), "\n", $text );

    // Find newlines in all elements and add placeholders.
    $text = wp_replace_in_html_tags( $text, array( "\n" => ' <!-- wpnl --> ' ) );

    // Remove more than two contiguous line breaks.
    $text = preg_replace( "/\n\n+/", "\n\n", $text );

    // Split up the contents into an array of strings, separated by double line breaks.
    $paragraphs = preg_split( '/\n\s*\n/', $text, -1, PREG_SPLIT_NO_EMPTY );

    // Reset $text prior to rebuilding.
    $text = '';

    // Rebuild the content as a string, wrapping text with a <p> while omitting html tags.

    $pattern = '/^(?!<(strong|a|em)\b)(<[^>]+>)/i';

    foreach ( $paragraphs as $paragraph ) {
        if ( preg_match( $pattern, $paragraph ) === 1 ) {
            $text .= trim( $paragraph, "\n" ) . "\n";
        } else {
            $text .= '<p>' . trim( $paragraph, "\n" ) . "</p>\n";
        }
    }

    // Under certain strange conditions it could create a P of entirely whitespace.
    $text = preg_replace( '|<p>\s*</p>|', '', $text );

    // Restore newlines in all elements.
    if ( false !== strpos( $text, '<!-- wpnl -->' ) ) {
        $text = str_replace( array( ' <!-- wpnl --> ', '<!-- wpnl -->' ), "\n", $text );
    }

    return $text;
}

remove_filter( 'the_content', 'wpautop' );
add_filter( 'the_content', 'wpautop_custom', 100, 1 );
```

To use this code, you can simply add it to your functions.php file. You can also modify $pattern to suit your needs.

Essentially, the wpautop_custom function adds double line breaks everywhere like the original wpautop function, but then only adds p tags to text and omits all html tags except when a line starts with strong, a or em.

With this function, I have no more issues with any type of embeds (Instagtam, Twitter) and my code passes W3C Html and Feed validators.

Maybe WordPress could have 2 wpautop functions, one "normal" (the default one) and one "simple" (something similar to what I suggested).

@jeherve, your input would be appreciated!

**Comment by jeherve** [comment]
> your input would be appreciated!

I'm wondering if it wouldn't be best to modify the output returned by those 2 embeds before they get passed through `wpautop`, and remove extra line breaks? I don't think we need those extra line breaks in the first place.

Looking at WordPress Core, they seem to have taken a similar approach years ago by hooking into `oembed_dataparse`:

- https://core.trac.wordpress.org/ticket/12115
- https://github.com/WordPress/WordPress/blob/9dc13e98d73c1917b2637613db34aab6d43deb27/wp-includes/class-wp-oembed.php#L746-L784
- https://developer.wordpress.org/reference/hooks/oembed_dataparse/

I'm not quite sure why that code isn't already solving our issue, though. I assume the response we get from Instagram does not include `\n`, but something else that gets transformed into a paragraph by `wpautop`?

Edit: in the case of `gist`, since we do not return an oembed that would explain why this code doesn't help us:
https://github.com/Automattic/jetpack/blob/3ff19e36551e19df74e26e87f9691846dfdd0be8/projects/plugins/jetpack/modules/shortcodes/gist.php#L205-L208

**Comment by janvitos** [comment]
> I assume the response we get from Instagram does not include `\n`, but something else that gets transformed into a paragraph by `wpautop`?

There are no \n or \r in Instagram embeds, it's just a single line of code. Here's an example Instagram embed:

```
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-permalink="https://www.instagram.com/p/CbBPmstLKkw/?utm_source=ig_embed&amp;utm_campaign=loading" data-instgrm-version="14" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:540px; min-width:326px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:16px;"> <a href="https://www.instagram.com/p/CbBPmstLKkw/?utm_source=ig_embed&amp;utm_campaign=loading" style=" background:#FFFFFF; line-height:0; padding:0 0; text-align:center; text-decoration:none; width:100%;" target="_blank"> <div style=" display: flex; flex-direction: row; align-items: center;"> <div style="background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 40px; margin-right: 14px; width: 40px;"></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 100px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 60px;"></div></div></div><div style="padding: 19% 0;"></div> <div style="display:block; height:50px; margin:0 auto 12px; width:50px;"><svg width="50px" height="50px" viewBox="0 0 60 60" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g transform="translate(-511.000000, -20.000000)" fill="#000000"><g><path d="M556.869,30.41 C554.814,30.41 553.148,32.076 553.148,34.131 C553.148,36.186 554.814,37.852 556.869,37.852 C558.924,37.852 560.59,36.186 560.59,34.131 C560.59,32.076 558.924,30.41 556.869,30.41 M541,60.657 C535.114,60.657 530.342,55.887 530.342,50 C530.342,44.114 535.114,39.342 541,39.342 C546.887,39.342 551.658,44.114 551.658,50 C551.658,55.887 546.887,60.657 541,60.657 M541,33.886 C532.1,33.886 524.886,41.1 524.886,50 C524.886,58.899 532.1,66.113 541,66.113 C549.9,66.113 557.115,58.899 557.115,50 C557.115,41.1 549.9,33.886 541,33.886 M565.378,62.101 C565.244,65.022 564.756,66.606 564.346,67.663 C563.803,69.06 563.154,70.057 562.106,71.106 C561.058,72.155 560.06,72.803 558.662,73.347 C557.607,73.757 556.021,74.244 553.102,74.378 C549.944,74.521 548.997,74.552 541,74.552 C533.003,74.552 532.056,74.521 528.898,74.378 C525.979,74.244 524.393,73.757 523.338,73.347 C521.94,72.803 520.942,72.155 519.894,71.106 C518.846,70.057 518.197,69.06 517.654,67.663 C517.244,66.606 516.755,65.022 516.623,62.101 C516.479,58.943 516.448,57.996 516.448,50 C516.448,42.003 516.479,41.056 516.623,37.899 C516.755,34.978 517.244,33.391 517.654,32.338 C518.197,30.938 518.846,29.942 519.894,28.894 C520.942,27.846 521.94,27.196 523.338,26.654 C524.393,26.244 525.979,25.756 528.898,25.623 C532.057,25.479 533.004,25.448 541,25.448 C548.997,25.448 549.943,25.479 553.102,25.623 C556.021,25.756 557.607,26.244 558.662,26.654 C560.06,27.196 561.058,27.846 562.106,28.894 C563.154,29.942 563.803,30.938 564.346,32.338 C564.756,33.391 565.244,34.978 565.378,37.899 C565.522,41.056 565.552,42.003 565.552,50 C565.552,57.996 565.522,58.943 565.378,62.101 M570.82,37.631 C570.674,34.438 570.167,32.258 569.425,30.349 C568.659,28.377 567.633,26.702 565.965,25.035 C564.297,23.368 562.623,22.342 560.652,21.575 C558.743,20.834 556.562,20.326 553.369,20.18 C550.169,20.033 549.148,20 541,20 C532.853,20 531.831,20.033 528.631,20.18 C525.438,20.326 523.257,20.834 521.349,21.575 C519.376,22.342 517.703,23.368 516.035,25.035 C514.368,26.702 513.342,28.377 512.574,30.349 C511.834,32.258 511.326,34.438 511.181,37.631 C511.035,40.831 511,41.851 511,50 C511,58.147 511.035,59.17 511.181,62.369 C511.326,65.562 511.834,67.743 512.574,69.651 C513.342,71.625 514.368,73.296 516.035,74.965 C517.703,76.634 519.376,77.658 521.349,78.425 C523.257,79.167 525.438,79.673 528.631,79.82 C531.831,79.965 532.853,80.001 541,80.001 C549.148,80.001 550.169,79.965 553.369,79.82 C556.562,79.673 558.743,79.167 560.652,78.425 C562.623,77.658 564.297,76.634 565.965,74.965 C567.633,73.296 568.659,71.625 569.425,69.651 C570.167,67.743 570.674,65.562 570.82,62.369 C570.966,59.17 571,58.147 571,50 C571,41.851 570.966,40.831 570.82,37.631"></path></g></g></g></svg></div><div style="padding-top: 8px;"> <div style=" color:#3897f0; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:550; line-height:18px;">View this post on Instagram</div></div><div style="padding: 12.5% 0;"></div> <div style="display: flex; flex-direction: row; margin-bottom: 14px; align-items: center;"><div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(0px) translateY(7px);"></div> <div style="background-color: #F4F4F4; height: 12.5px; transform: rotate(-45deg) translateX(3px) translateY(1px); width: 12.5px; flex-grow: 0; margin-right: 14px; margin-left: 2px;"></div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(9px) translateY(-18px);"></div></div><div style="margin-left: 8px;"> <div style=" background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 20px; width: 20px;"></div> <div style=" width: 0; height: 0; border-top: 2px solid transparent; border-left: 6px solid #f4f4f4; border-bottom: 2px solid transparent; transform: translateX(16px) translateY(-4px) rotate(30deg)"></div></div><div style="margin-left: auto;"> <div style=" width: 0px; border-top: 8px solid #F4F4F4; border-right: 8px solid transparent; transform: translateY(16px);"></div> <div style=" background-color: #F4F4F4; flex-grow: 0; height: 12px; width: 16px; transform: translateY(-4px);"></div> <div style=" width: 0; height: 0; border-top: 8px solid #F4F4F4; border-left: 8px solid transparent; transform: translateY(-4px) translateX(8px);"></div></div></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center; margin-bottom: 24px;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 224px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 144px;"></div></div></a><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/CbBPmstLKkw/?utm_source=ig_embed&amp;utm_campaign=loading" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">A post shared by ipnoze (@ipnozeofficiel)</a></p></div></blockquote> <script async src="//www.instagram.com/embed.js"></script>
```

Unfortunately, I wasn't able to figure out what was causing the extra <\/p> tags to be added by wpautop, so that's why I decided to rebuild the function.

**Comment by jeherve** [comment]
> I wasn't able to figure out what was causing the extra </p> tags to be added by wpautop

Could it be the spaces inside the `a` tag? What if we removed those spaces upon receiving the response from Instagram?
