### ISSUE TITLE
Carousel: Two images will overlap/lay if you scroll through

### ISSUE THREAD

**Issue by kathleenjross** [Automattic/jetpack#20199]
#### Steps to reproduce the issue

1. Go to new page or post
2. Add a Gallery block with **two images only**
3. Publish and view live. Click the gallery to open the carousel slideshow
4. Click through the slideshow, from first to second image, back to the first image. The second image will now appear behind the first image almost as an overlay or faint background.

#### What I expected

The second image should not appear the first. This does not happen if the gallery block has more than 2 images.

#### What happened instead

Example:
<img width="1164" alt="Screen Shot 2021-06-28 at 9 18 30 AM" src="https://user-images.githubusercontent.com/14097527/123643007-f1dfd380-d7f1-11eb-9e7d-6b4c6f451c22.png">

Discovered in 190692260-hc and replicated on test site.

**Comment by jeherve** [comment]
We're about to release a new version of the Carousel feature, that should solve that issue. Would you mind trying to install [the Jetpack Beta plugin](https://jetpack.com/beta) on your site, and search for the "refactor/carousel-to-use-swiper" branch under Jetpack > Beta? Let us know if when doing so, the problem disappears!

Thanks!

**Comment by happychait** [comment]
@jeherve 

We had a user report which I replicated [in my test post with only two images on a Gallery block](https://chaittestpress.com/2021/07/06/eris-exif/): the overlap issue as well as missing EXIF data on the carousel as following:
![background overlap](https://user-images.githubusercontent.com/1519466/124532380-8686a900-de64-11eb-9f8b-908ab013dd8d.png)

Both problems won't happen if the Gallery has more than two images as [in this other test post](https://chaittestpress.com/2021/07/06/gallery-w-more-than-2-images-exif-no-issue/). Gallery navigates without overlap on the images and also displays the EXIF data for all three images. All the images are the same in both posts.

Something odd seems to be happening with only two images on the Gallery block.

**Comment by sdixon194** [comment]
@happychait it looks like that site is also still using the gallery before the new carousel update. That's releasing in Jetpack 9.9 today, so I would try again in a few hours when a new version of Jetpack is released if they don't want to [try the beta plugin](https://jetpack.com/beta/).

**Comment by happychait** [comment]
@sdixon194 This is for a Simple site and the problem still exists on [my test post with two images on the gallery](https://chaittestpress.com/2021/07/06/eris-exif/), but all good on [another test post with more than two images on the gallery](https://chaittestpress.com/2021/07/06/gallery-w-more-than-2-images-exif-no-issue/).

**Comment by sdixon194** [comment]
@happychait ah apologies, missed that was on a simple site. The changes here haven't been ported to WordPress.com simple sites yet, but should be good to go very soon. I'd double check tomorrow/the day after.

**Comment by Robertght** [comment]
Another case in 4119618-zen and it's still an issue

Simple site.

**Comment by happychait** [comment]
@sdixon194 Just wondering if we have got any update on this yet, for Simple sites.

**Comment by sdixon194** [comment]
@happychait Just looked and seems like they're still working on the wpcom batch. I'll let you know as soon as there's an update. Thanks for your patience!

**Comment by happychait** [comment]
I tested and confirm this bug is fixed and no longer happening on my earlier test post: https://chaittestpress.com/2021/07/06/eris-exif/

This is good to close.
