### ISSUE TITLE
4.0: Fatal Error when updating

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3697]
In some cases, updating to Jetpack 4.0 returns the following Fatal Error:

```
Fatal error: Cannot find a library with slug class.media-summary. in /home/XXXXXXXXXXX/wp-content/plugins/jetpack/require-lib.php on line 35.
```

This was most likely introduced when we moved the file to a different location, in #2963.

The solution might be to create an empty file in the old location, as we had done in 8c3790d8cb1463a687a250b6b3d687c03a0365ca for the Jetpack Debugger.

**Comment by jeherve** [comment]
https://wordpress.org/support/topic/jetpack-blank-screen-after-updating-to-new-version
https://wordpress.org/support/topic/white-screen-of-death-upon-upgrading-to-40
https://wordpress.org/support/topic/blank-page-after-upgrade-to-40
https://wordpress.org/support/topic/help-new-update-ruined-my-site
https://wordpress.org/support/topic/http-error-5000-internal-server-error-5
https://wordpress.org/support/topic/version-40-caused-a-500-error
https://wordpress.org/support/topic/getting-fatal-error-message-2
https://wordpress.org/support/topic/jetpack-400-500-error-temporary-fix

**Comment by slaFFik** [comment]
Have broken site as well. Error 500. Broken only if connected to wp.com. Admin area works as expected.

**Comment by jeherve** [comment]
@slaFFik Sorry about that! Could you try to completely deactivate and delete the plugin, and then reinstall from scratch from the Plugins menu in your dashboard, and let me know if it helps?

**Comment by slaFFik** [comment]
Deactivation doesn't help. 
https://wordpress.org/support/topic/jetpack-400-500-error-temporary-fix?replies=5#post-8309450 fixed the issue.

**Comment by jeherve** [comment]
Just to be clear, have you tried to delete the plugin altogether as well?

**Comment by mhlick** [comment]
I've got the same issue. I've deleted Jetpack and reinstalled it and everything is fine

**Comment by gloubibou** [comment]
Fixed on [my blog](https://blog.houdah.com) by disabling Publicize.

Publicize was connected only to Google+. Disconnecting and reconnecting as fixed Publicize.
I am again running with Publicize enabled.

**Comment by brianhogg** [comment]
As a note, I'm getting a slightly different error but likely related:

`Fatal error: Cannot find a library with slug admin-pages/class.jetpack-landing-page. in /nas/content/live/drscott/wp-content/plugins/jetpack/require-lib.php on line 35`

**Comment by jeherve** [comment]
@brianhogg Could you let us know what version of Jetpack you're running? We've just released Jetpack 4.0.2 to address this issue.

**Comment by brianhogg** [comment]
@jeherve this was 4.0.1.  Just updated to 4.0.2 and activated without issue!

**Comment by kat0616** [comment]
so I did the update, and got a error when tryign to go into /wp-admin on line35, however I went into my file manager deleted jetpack, and then went back into my website and re installed, and seems to be working completely fine now...And it still shows all my old setup, which is cool, cause I thought once deleted everything would be gone

**Comment by JudyVandiver** [comment]
I am having same problem. I can not get into my wordpress screen AT ALL. On cpanel, I do not know if I can delete jetpack from there. I need help.  Have worked on this new site for 6 weeks, inputting data and products. Was set to go live in 5 days. No way can I rebuild this. I need help. judy@judyvandiver.com.  Site is marieetoile.com

**Comment by jeherve** [comment]
@JudyVandiver Could you try to log in to your site via FTP or CPanel, and delete the existing Jetpack plugin folder?

You'll find the Jetpack plugin folder here:
`
wp-content
   plugins
     jetpack - DELETE THIS FOLDER
`

If you're not sure how to do this, you can ask your hosting company for help. They should also have documentation explaining how to edit or remove files from your site using FTP or a File Manager in your admin panel.

Once you've done so, you'll be able to access your dashboard again, and then go to Plugins > Add New to install Jetpack again.

**Comment by JudyVandiver** [comment]
@jeherve 
I have cpanel open ... Looking... Ok... found jetpack plug in... deleting... I"M IN!!!!!  Thank you so very very much.  If I install Jetpack again, will it crash it again???

**Comment by jeherve** [comment]
As long as you install the most recent version of Jetpack (4.0.2), you shouldn't run into any issues!

**Comment by JudyVandiver** [comment]
@jeherve... Ok... thank you so very much. PPL think I'm tech savvy, but only to a point, then I need help from the real tech savvy ppl.  But if you want to buy homemade soaps and bath products, my new site marieetoile.com will be the place to go. Soaps I know. Tech stuff - only to a point.  Going live in one week, right after hubby's cancer surgery.  Again... Thank you.

**Comment by kat0616** [comment]
I couldn't pull it thru my website at all, I had to go to hostgator and go into the c panel, then file manager, then plugs, then on the right in the blue folders found jetpack and deleted it.

**Comment by Yan-Alexandre** [comment]
Hello, tried with Jetpack 4.0.2 and still have the same issue : blank page on the front end and backoffice.

**Comment by jeherve** [comment]
@Yan-Alexandre I'm sorry to hear you've run into issues.

Could you check your server error logs around the time when you experienced the issue, to find out more about the error?

If you don't know how to access your server error logs, your hosting provider should be able to help.

You can send us the errors you find via this contact form:
http://jetpack.com/contact-support/

**Comment by Yan-Alexandre** [comment]
@jeherve  thanks for you reply, unfortunatly my server error log is empty...
Any idea how we can monitor these trouble ? Maybe à WP code to track php errors ?

(my website is www.blenheimgang.com, but I suppose you won't see any problems going there)

**Comment by jeherve** [comment]
>  Maybe à WP code to track php errors ?

Yes. Could you add the following to your site's wp-config.php file? 

```php
define('WP_DEBUG', true);

if ( WP_DEBUG ) {

        @error_reporting( E_ALL );
        @ini_set( 'log_errors', true );
        @ini_set( 'log_errors_max_len', '0' );

        define( 'WP_DEBUG_LOG', true );
        define('WP_DEBUG_DISPLAY', false);
        define( 'CONCATENATE_SCRIPTS', false );
        define( 'SAVEQUERIES', true );

}
```
Once you've done so, try reloading your site and then check the `wp-content/debug.log` file for errors.
You can send us the results via the form I linked to above, and then replace `define('WP_DEBUG', true);` by `define('WP_DEBUG', false);` in the code above.

**Comment by tigermucha** [comment]
I just had this happen to my blog - not experienced with code but I did figure out how to delete from my server.  When I reinstalled it crashed my blog again.  So I had to delete again from my server.  It all started Saturday when I went to update the plugin because it said it had an update.  Then I got the server error and lost access to my admin dashboard and all visibility to the blog.

I freaked but thankfully I came across this.  After deleting the second time I can see my blog and I can access my dashboard and hopefully get back to running my blog again.  But I won't be installing Jetpack again until I hear that whatever is causing this is fixed.  It is very scary to lose access to something that is so important to me.

Thanks for the directions on how to delete the folder.
Teresa

**Comment by jeherve** [comment]
@tigermucha This issue was fixed back in April, in Jetpack 4.0.2. Could you make sure that you're running the most recent version of the Jetpack plugin on your site?

If you do, could you make sure WordPress is also up to date?

You should then be able to activate Jetpack again. If you keep experiencing issues, could you post the error you're seeing here?

Thanks!

**Comment by tigermucha** [comment]
@jeherve Hi yes, I do have the most current Wordpress updated. It still didn't work. If I decide to add it back and get an error I will let you know. Right now I am just happy to have access back.

**Comment by mckennedy** [comment]
I'm getting:

Fatal error: Uncaught Error: Call to undefined function wp_parse_url()

/wp-content/plugins/jetpack/class.jetpack.php:5420

**Comment by dereksmart** [comment]
@mckennedy what version of WP are you running? that is a core function and was introduced in 4.0.

**Comment by mckennedy** [comment]
yeah that fixed it. forgot to check locally. i was on 4.3.1 where production was 4.7
