### ISSUE TITLE
Related Posts: conflict with Polylang 

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7203]
#### Steps to reproduce the issue

1. Install Jetpack and activate Related Posts.
2. Install and activate the Polylang plugin.
3. Go to Languages, create a new default language, and assign all your posts to that language.
4. Create an additional language, no need to assign any posts to that one yet.
5. Visit one of your posts => Related Posts are gone.

This used to work in the past, but doesn't anymore.

The problem seems to be linked to a specific function used in Polylang to make sure Related Posts match the language used in the original post:
- https://github.com/polylang/polylang/blob/2.1.4/modules/plugins/plugins-compat.php#L46
- https://github.com/polylang/polylang/blob/2.1.4/modules/plugins/plugins-compat.php#L607-L621

Commenting this out solves the issue.

This function was added to Polylang after discussion with us, and worked at the time. See p3py7Y-C7-p2 and 2487669-t for earlier discussions about this.

cc @gibrown since you worked on the original request. Did ElasticSearch's syntax for languages change, maybe?

Related: #3280

**Comment by jeherve** [comment]
Reported here:
https://wordpress.org/support/topic/related-posts-not-showing-15/

**Comment by jeherve** [comment]
cc @Chouby, Polylang author; just in case you receive reports about issues with Related Posts on your end!

**Comment by gibrown** [comment]
Ya, we've been working on a fix for this issue for a little while. Root problem is that we've hit some scaling issues with Elasticsearch and the total number of fields you can have. Storing custom taxonomies as taxonomy.*.slug means we've started to hit some limits at 200k+ fields.

For some subset of sites, they are probably working ok, but some do not currently have all of their custom taxonomy information in the index.

We have a more permanent fix, but it will probably be a few weeks before we can get it fully deployed because we have to rebuild the entire index which takes at least a two weeks (and probably longer due to some other issues). We'll see if we can get a work around in place for this particular user/plugin.

**Comment by stevekaeser** [comment]
I was able to reproduce using the steps above and I see that this is the filter that is used by polylang:

```
{
  "size":3,
  "filter":{
    "and":[
      {
        "term": {
          "post_type":"post"
        }
      },
     {
       "term": {
         "taxonomy.language.slug":"english"
       }
     }
   ]
  }
}
```

But this is what is indexed for the language taxonomy:

```
"language": [
  {
    "name": "English",
    "slug": "en",
    "term_id": "3"
  }
]
```

So, the reason that related posts aren't coming back is because it's searching for the slug **english** instead of the **en**

**Comment by stevekaeser** [comment]
I have created a pull request that fixes this is polylang:

https://github.com/polylang/polylang/pull/135

you can see the results of these changes on this post from my test site:

http://blog.parks-place.com/en/the-iron-fist/

**Comment by Chouby** [comment]
@jeherve Thanks for pinging me.

@gibrown So if I well understand: Up to now, you stored only the term name on the Jetpack server and thus could not take into account a customized term slug (such as **en** for **English**). And starting from now, you are storing the term slug as it is in the WordPress site. Am I right? Do we need a specific Jetpack version for this to work or did this all happen only on the Jetpack server?

@stevekaeser Thanks for the PR :)

**Comment by RCowles** [comment]
The user in 975211-zen reported that Related Posts do not show when Polylang is active. The issue occurs with posts in both English and German, so it does not seem to be limited to a specific language.  Related Posts show in the Customizer for both languages, but do not appear on the live site.

@jeherve does this sound like the same issue you originally reported above?

**Comment by jeherve** [comment]
Yes, although we've made some more changes to Jetpack in 5.8 that may fix their problem. I would recommend updating to the most recent version of Jetpack, scheduling a full sync, and waiting for 12 hours for the cache to clear.

Related: 1598-gh-jpop-issues

**Comment by TheSteveK** [comment]
a user came back to report polylang updated and the issue resurfaced in 1223575-zen I went ahead and commented out the same line mentioned in 1598-GH to get them working again.

**Comment by gsmumbo** [comment]
We have another user with this issue in 1240776-zen. The code that was commented out before is no longer there. Can @gibrown or @stevekaeser take a look? They were also using acf-options-for-polylang-master and Loco Translate but have since disabled them and it didn't fix the issue.

**Comment by StefMattana** [comment]
Do we have any news about this bug? I still have a user on 1240776-zen waiting for an update. I'm going to follow up with them meanwhile.

**Comment by chickenn00dle** [comment]
We have another case of this here 2304697-zen. It also looks like this was never addressed in 1240776-zen above. 

Any updates on whether this will be worked on @jeherve, or are we just accepting problem cases as known conflicts?

**Comment by jeherve** [comment]
No updates so far, but we'll update this issue when we do start to work on this.

**Comment by jeherve** [comment]
@ICEknigh7 You may be able to use the `jetpack_relatedposts_filter_headline` filter to customize the Related headline that's displayed above related posts.

You can find out more about how to use it here:
https://developer.jetpack.com/hooks/jetpack_relatedposts_filter_headline/

@Chouby Do you think it would make sense to add an option in Polylang so folks can enter different Related Posts Headline values for each language?

**Comment by supernovia** [comment]
Hey folks, noting we have another case here:
https://wordpress.org/support/topic/only-old-posts-show-up-in-related-posts/

**Comment by physixfan** [comment]
@Chouby Please take a look again at this issue, thanks! This issue is still here... https://wordpress.org/support/topic/only-old-posts-show-up-in-related-posts/

**Comment by csonnek** [comment]
Another in 3067138-zen

**Comment by physixfan** [comment]
The author of Polylang says: “ The related posts are evaluated on the Jetpack servers. If something is changed in the way it is done, there is no way for us to know, and no way for us to know what to do.” https://github.com/polylang/polylang/issues/594#issuecomment-755214366

So please, take a look again, or communicate with each other, thanks very much!

**Comment by physixfan** [comment]
> @physixfan This issue is referring to related posts matching the wrong language, as set in Polylang. In [the forum thread you mentioned above](https://wordpress.org/support/topic/only-old-posts-show-up-in-related-posts/), you seem to be experiencing a different issue with all your new posts missing Related Posts. Is that correct? Is this happening regardless of the language of the post on your site?
> 
> If you have more details, do you think you could contact us via [this contact form](https://jetpack.com/contact-support/?rel=support&hpi=1), so we can look into this further with you? It could be that your problem is different from the one we're discussing on this GitHub issue.
> 
> Thank you.

Yes, you are right, maybe our problem is different from this Github issue. I can't remember why I was redirected here. Anyway I've contacted you guys via contact form.

**Comment by RavanH** [comment]
Hi, I think I've run into this issue but not really sure. We have one site with Polylang and Jetpack Related Posts just working fine together. But another where Jetpack Related Posts will only work when Polylang is disabled.

The working site has run both Polylang and Jetpack Related Posts from day one but the site with the issue was built with Jetpack Related Posts from the start but Polylang was added just recently. All existing posts were assigned to the (new) default language, all taxonomy terms and some posts have been translated.

Not sure if the issue started immediately after activating Polylang or only later. Maybe after all taxonomy terms got translated, somehow hitting the taxonomy slug issue mentioned by @gibrown above? If so, is there any way to trigger a re-indexation of the problematic site?

**Comment by jeherve** [comment]
@RavanH Could you [contact us via email](https://jetpack.com/contact-support/?rel=support&hpi=1), and mention this GitHub issue as well as the site URL? We'll see what we can do to reindex things.

Thank you!

**Comment by pehaa** [comment]
@jeherve - @RavanH contacted us via 9459537-zen (site url in the ticket) Thank you!

**Comment by jeherve** [comment]
I see there are some connection issues with the site right now. Once that's solved, we'll attempt to synchronize things again.

**Comment by jos22** [comment]
@jeherve user in 9459537-zd-a8c appears to be set connection-wise. Can you have a look? Thanks!

**Comment by RavanH** [comment]
So I finally had to comment out line https://github.com/polylang/polylang/blob/3.6.x/integrations/jetpack/jetpack.php#L22 to fix the issue.

The weird thing is that on another site (with the same plugins and theme running) this issue does not occur and no comment-out-fix is needed. The only difference I can think of is that on the site without the issue, we had Polylang running from the start and added Related Posts at a later stage. While on the failing site, we had Related Posts running long before we finally added Polylang.

Could this order of activation have such an impact? Hard to imagine but...

**Comment by RavanH** [comment]
I should also mention that with the work-around commenting out https://github.com/polylang/polylang/blob/3.6.x/integrations/jetpack/jetpack.php#L22 while the related posts start working again, languages in these related posts are mixed: suggestions from other languages than the post itself appear in the Related Posts block.

Not as it should be, but better than no related posts at all I suppose. But maybe not optimal in terms of SEO?
