### ISSUE TITLE
Issue with JetPack DB entries causing slow page refresh

### ISSUE THREAD

**Issue by weavertheme** [Automattic/jetpack#7439]
#### Steps to reproduce the issue

See http://fdev.weavertheme.com using Chrome or Firefox. Windows browsers seem unaffected.

#### What I expected

Normal, fast page refreshing/generation. As is currently found at http://forum.weavertheme.com that currently has JetPack disabled. The two sites are essentially identical other than having JetPack enabled or disabled. Of course the live site will get new posts, while the fdev version is now static.

#### What happened instead

Note how the page refreshes really badly. Some parts show up immediately (images, links, boldface and other things), and then after some delay, the rest fills in.

#### What I did to fix it

Disabling JetPack fixed the issue on my main support forum. I cloned the site, and the problem continues. I can't make the problem appear on any new site, nor does it appear on my other sites. It is unique to my forum, and it just showed up within the past week.

I disable all but JetPack and my theme, and the problem is still there. So, I concluded it must be a JetPack issue. I can disable JetPack, reactivate (and re-link to my WordPress.com account), and the page refresh problem comes back.

So, this left the likelihood that there was something broken in the database. This proved to be true. After disabling JetPack, I went through the entire site database and deleted any and all rows in the wp_options table that had JetPack or jp in them. Lots and lots of theme. Many with transient. After this exercise, I reactivated JetPack, and the page refresh issue was gone. So some setting - perhaps a sync or transient setting - was causing that very strange refresh behavior you can see in my demo site.

I can't tell you specifically which entry may have been causing the issue - I just blindly deleted all of them.

#### Possible simple solution

Is there a plugin that will clean up ALL JetPack wp_option entires? Would be nice. You generate a lot of rows, and if one wants to clean up the DB, it would really be nice if they could go away!

#### How can you test this?

My http://fdev.weavertheme.com site current retains the issue with JetPack enabled. I can give you full admin access to the site, but probably not cPanel access. I have an image of the site, so can easily restore it to the full site if need be.

The site was cloned from a pretty large bbPress site. The issue is still there with bbPress deactivated. I have attached an SQL dump of the options table with the problem JetPack options.

[wp_options.sql.gz](https://github.com/Automattic/jetpack/files/1133386/wp_options.sql.gz)

**Comment by zinigor** [comment]
Hello! Thank you for reporting your issue!
It looks like you maybe experiencing #7435. I have taken a look at the options table dump, and it looks OK after a cursory glance. There's a proposed patch for the issue: #7446, we'd really appreciate it if you could test it for us. You can do that by using the [Jetpack Beta plugin](https://jetpack.com/beta/).

I'm going to close this one, but feel free to reopen if you have problems that are not solved by the patch I have linked to.

**Comment by weavertheme** [comment]
I just installed and activate the bleeding edge of JetPack Beta.

This did NOT fix the issue. I was running with the existing DB entries on my live Forum site, and did NOT clear out all the JetPack DB entries as described above.

So for me, this is still an issue. I do wish there was a way to clear out all JetPack DB rows.

**Comment by zinigor** [comment]
@weavertheme thanks for trying the Beta plugin, we really appreciate it!

Can you please try to profile the database queries and see which of them take that much time? You can use John Blackbourn's [Query Monitor](https://wordpress.org/plugins/query-monitor/) to see what queries are getting run on the page. You can sort queries by time and see the ones that take the longest to complete. We'd be very grateful if you paste the results here, or into a pastebin.

**Comment by zinigor** [comment]
@weavertheme I have just realized that in order to test the fix it's not enough to use "Bleeding Edge". You need to switch to #7446 specifically because it's not yet in Bleeding Edge. Can you please try that first?

Thanks!
