### ISSUE TITLE
Subscriptions: include CPTs

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#760]
Currently, the subscriptions module will only notify subscribers when a new post is made on the blog.

Since WP 3.0, CPTs (custom-post-types) have started playing an increasingly dominant role in many blogs. Therefore, I believe it would be a great addition to Jetpack to add the option for blog admins to select which post types will be included in these updates.

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/1937

**Comment by chaselivingston** [comment]
Requested in 2096887-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/subscriptions-jobs-events?replies=1&view=all

**Comment by mikeyarce** [comment]
Also suggested here:
2180609-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/ssubscriptions-for-custom-post-types?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/jetpack-subscribe-email-notifications-for-events?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/subscriber-email-notifications-for-different-content-types?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here: 2091078-t

**Comment by richardmtl** [comment]
requested in 2282088-t

**Comment by richardmtl** [comment]
requested in 2305017-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/subscritions-and-marketpress-not-compatible?replies=1&view=all

**Comment by RCowles** [comment]
Suggested in 2447672-t

**Comment by KokkieH** [comment]
Another request here: https://twitter.com/user/status/685770900835295232

**Comment by lschuyler** [comment]
Requested in 2497836-t

**Comment by ebinnion** [comment]
Requested in 2605489-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/how-can-i-subscribe-to-receive-the-new-articles-the-new-events?replies=1&view=all

**Comment by annezazuu** [comment]
Requested in 2692774-t

**Comment by v18** [comment]
2693275-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/comment-subscription-custom-post-type?replies=1&view=all

**Comment by RCowles** [comment]
2643878-t

**Comment by RCowles** [comment]
2735963-t

**Comment by thedodd** [comment]
This would be extremely useful for basic CPTs. My team is using the [json rest api subscriptions](https://wordpress.org/plugins/json-rest-api-subscriptions/) plugin, and being able to receive events programmatically for CPTs would be awesome.

Any suggestions on what can be done to get events for custom types working right now? Maybe just a pointer to some code that I can hack. Anything really.

**Comment by jeherve** [comment]
> Any suggestions on what can be done to get events for custom types working right now? Maybe just a pointer to some code that I can hack. Anything really.

Since the subscriptions are sent from WordPress.com, I'm afraid you won't be able to contribute; it's something we'll need to develop on WordPress.com first.

We'll update this issue as soon as we start working on this!

**Comment by thedodd** [comment]
@jeherve thanks for the quick response. I suspected that such was the case. I'll keep an eye on this thread then.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/subscriber-notification-emails-for-portfolio-projects-instead-of-posts?replies=1

**Comment by rockstarwebdesign** [comment]
It would be great to notify subscribers when a new CPT is published...

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/auto-sharing-for-job-boards-jobmonster-theme/

**Comment by lamdayap** [comment]
2885990-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/email-subscriptions-for-custom-posts/

**Comment by VladAntropov** [comment]
Is there a workaround for this issue?

**Comment by nicmare** [comment]
two years later nothing has changed yet :(. theres no workaround because the subscriptions are managed over the wordpress servers.

**Comment by jeherve** [comment]
@VladAntropov There is no work around. As @nicmare mentioned, the emails are sent from WordPress.com servers. It's consequently not possible to enable subscriptions emails for Custom Post Types with a simple change in the code on your own site.

If you'd like to send out subscription emails for Custom Post Types, I'd recommend that you use a different subscription service, like [MailPoet](https://www.mailpoet.com/) or [Mailchimp](http://mailchimp.com/).

**Comment by superkierowca** [comment]
@jeherve What can I add to the subject... After two years of seduction the only word JetPack Team says to users is to use third-party service for CPT mail notifications? People want that functionality as CPT are core format of many modern themes. Do you really like us to uninstall JetPack in favour of MailChimp? I personally would rather stay with JetPack but how can I as my site has regularly published CPT's in plans ? Come on :)

**Comment by jeherve** [comment]
@superkierowca I'd love to tell you Jetpack Subscriptions will support Custom Post Types very soon, but I'd be lying.

As mentioned earlier on this issue, enabling subscriptions for CPTs will require some planning as a lot of CPTs rely on custom post meta and other custom implementations to display content. That's not on our roadmap yet, so it's best if you use a third-party tool if you need that functionality right now.

That said, you don't have to uninstall Jetpack; you can deactivate the Subscriptions module and keep using the other features in Jetpack.

We'll update this issue as soon as this gets on our roadmap and we start working on it.

**Comment by ghrem988** [comment]
While I understand that JetPack team is busy and has to prioritize fixes, I expect the evolution of JetPack plugin not to fall too far behind WordPress's overall evolution.  CPT is as core and as significant as anything WordPress does today and yet JetPack does not seem to think it is. Also it makes you wonder that JetPack still lives in the world of WordPress as simple blog CMS and nothing more.

**Comment by csonnek** [comment]
Also requested in 2998342-t.

**Comment by defries** [comment]
>As mentioned earlier on this issue, enabling subscriptions for CPTs will require some planning as a lot of CPTs rely on custom post meta and other custom implementations to display content. That's not on our roadmap yet, so it's best if you use a third-party tool if you need that functionality right now.

I get that there a plenty of CPTs out there where this is the case. However, there are also plenty of CPTs that would work just fine if they were treated as regular WordPress posts. Why not make this an option to be activated by a developer as apposed to a settings somewhere. 

From my perspective this would create a nice middle ground instead of maintaining this somewhat ridiculous stance of "noted, but we're not doing anything to move forward for two years now".

**Comment by pmciano** [comment]
3019681-t

**Comment by csonnek** [comment]
Requested in 3086327-t

**Comment by lamdayap** [comment]
requested 3143224-t

**Comment by codestor4** [comment]
requested 3202917-t

**Comment by annezazu** [comment]
3252447-t

**Comment by annezazu** [comment]
Would be really neat to put this in place for WPJM cc @jom and @davoraltman

**Comment by cecoates** [comment]
612459-zen

**Comment by NujabesSoul** [comment]
Requested 697933-zen

**Comment by seejacobscott** [comment]
requested in 754461-zen

**Comment by richardmtl** [comment]
Requested in https://wordpress.org/support/topic/how-to-include-jetpack-portfolio-projects-in-jetpack-email-subscriptions/

**Comment by richardmtl** [comment]
921071-zen

**Comment by ntpixels** [comment]
938726-zen

**Comment by tmmbecker** [comment]
requested in https://wordpress.org/support/topic/how-to-manage-notify-me-of-follow-up-comments-by-email-for-custom-post-type/

**Comment by ntpixels** [comment]
1094364-zen

**Comment by rvpatel** [comment]
https://wordpress.org/support/topic/how-to-manage-notify-me-of-follow-up-comments-by-email-for-custom-post-type/
@erania-pinnera and @tmmbecker

Please provide a options for post type selection where you have need **Notify me of follow-up comments by email** 

\jetpack\modules\subscriptions.php line no 616
`
if ( FALSE === has_filter( 'comment_form', 'show_subscription_checkbox' ) && 1 == get_option( 'stc_enabled', 1 ) && empty( $post->post_password ) && 'post' == get_post_type() ) {`

There have not any filter function for change the code. Can we apply on custom post type?

**Comment by jeherve** [comment]
> There have not any filter function for change the code. Can we apply on custom post type?

Adding a filter here or changing the code in the plugin won't help I'm afraid. We would need to add support for Custom Post Types on WordPress.com first, where the emails are generated and sent.

We will update this issue once we make progress on this.

**Comment by coder-karen** [comment]
Requested in 1388180-zen

**Comment by pmciano** [comment]
Requested in 1677630-zen

**Comment by mfigrs** [comment]
After 4.5 years since the original issue, it is quite disappointing that Jetpack still can't send notification on CPTs - not even a post title and link.

Is there a way to make a CPT pretend to be a regular post for Jetpack?

**Comment by rockstarwebdesign** [comment]
And that is? Maybe for the year 2030? :(

**Comment by mzakariya** [comment]
Requested in 1905752-zen.

**Comment by tmmbecker** [comment]
Still a request.

**Comment by rockstarwebdesign** [comment]
Yes, still a request, after all these years. Would be nice to know it has been addressed : (

**Comment by createscape** [comment]
Hello, I would like to request this feature as well.

**Comment by BrookeDot** [comment]
VIP client request in 109953-zd-wordpressvip.

**Comment by sophiegyo** [comment]
We had a user who was asking after this in 3535140-zen as well today.

**Comment by w33zy** [comment]
It is 2021 and this is still an issue. 

If only there was a way we could tie this issue to something that Gutenberg needs... it would've been resolved within the hour.

**Comment by Kevin-Hamilton** [comment]
@jeherve who would be the best person to lobby for getting this onto the roadmap?  What would be the best method for contacting that person?

**Comment by jeherve** [comment]
@Kevin-Hamilton You're in the right place! This is where we track and monitor bugs as well as feature requests for Jetpack. 

We're not currently working on the Subscriptions feature, hence why this issue has remained opened for so long without any updates. When we do start iterating on the Subscriptions feature again, we'll look at feature requests just like this one to help us prioritize.

As my colleague mentioned above when we first discussed this feature, Custom Post Types in WordPress often rely on a custom content structure. When defining a new post type, and as you most likely know, one can choose whether they want to use post titles or not. They may also decide to rely on custom taxonomies or custom post meta instead of storing the main content in the post content area. This does make things a bit more difficult, as we would have to make assumptions that may not be correct when building the title and body of the email that needs to be sent.

In any case, until we start working on this, I can only recommend that you turn towards a different plugin to handle email subscriptions for Custom Post Types. [MailPoet](https://wordpress.org/plugins/mailpoet/), for example, supports Custom Post Types. While it doesn't work exactly like Jetpack's Subscriptions feature, it may fit your needs.

**Comment by w33zy** [comment]
@jeherve 

> When defining a new post type, and as you most likely know, one can choose whether they want to use post titles or not. They may also decide to rely on custom taxonomies or custom post meta instead of storing the main content in the post content area. This does make things a bit more difficult, as we would have to make assumptions that may not be correct when building the title and body of the email that needs to be sent.

Wouldn't all of the above be remedied by filters and actions? I mean, all you guys have to do is work with the post title and post content as usual, the provide appropriate hooks to these pieces of info. 

Hooks are what makes WordPress so powerful, and this is a WordPress plugin.

**Comment by jeherve** [comment]
@w33zy That certainly would be an option, although it would be a departure from the way Subscriptions work today; the feature doesn't require any configuration, it works out of the box.

**Comment by w33zy** [comment]
> ...it would be a departure from the way Subscriptions work today; the feature doesn't require any configuration, it works out of the box.

@jeherve 

You've either missed my point entirely (or you are deliberately dodging it). I specifically referenced using a hook (filter) to solve this issue. How would adding a filter affect the way the subscription module currently works? 

Isn't the idea behind WordPress hooks to provide customization to 1% of WP users who are comfortable enough with PHP to write custom code, while allowing the 99% to use WordPress as it was designed?

Are there not any filters in the entirety of Jetpack's codebase?

**Comment by jeherve** [comment]
Sorry, I should have been clearer. Let me try to rephrase.

Today, the Subscriptions feature doesn't require any kind of configuration; you can toggle the feature on and newly published posts will be sent to your subscribers.
Ideally, if one wanted to enable subscription emails for Custom Post Types on their site, the default behaviour would be the same as for Posts. They would enable a toggle for that post type and wouldn't have to do anything else; it would "just work".

For the reasons we've discussed above, that's not an option right now.

Offering the option to enable subscriptions for CPTs via a hook would be an alternative to a full-fledged UI, as you suggested. A simple filter in the plugin wouldn't be enough, as discussed in earlier comments on this issue, but with changes on WordPress.com (where content is processed and where the emails are being sent), it could be possible.

However, it would make that CPT option only available to subset of Jetpack site owners. As you mentioned, this would only be available to people comfortable enough with PHP to write custom code. That's where it would be a departure from the way the Subscriptions works today.

In any case, pushing out emails from Custom Post Types is something we'll consider when we next iterate on the Subscriptions feature. We'll update this issue when we make progress on this.

I hope this clarifies things a bit.

**Comment by renehesse** [comment]
Is there any news on this already? It's a pity not to be able to use the subscriptions at CPT, even if they correspond to "normal" posts. CPT are generally very poorly supported, until today they are not usable in the wordpress app. CPT are an important tool in wordpress.

**Comment by brianshim** [comment]
Would love to have the ability for users to subscribe to comments on Pages, thanks.

**Comment by julsyd** [comment]
Requested in 6039181-zen

**Comment by bobmatyas** [comment]
Requested on 6171491-zen

**Comment by Sobia-gh** [comment]
I saw a solution here: https://wordpress.stackexchange.com/questions/198378/how-to-allow-users-to-write-jetpack-custom-post-types

**Comment by jeherve** [comment]
@Sobia-gh This post isn't related to Jetpack's Subscriptions feature. It is about another Jetpack feature, [Jetpack Social](https://jetpack.com/support/jetpack-social/).

It is still not possible to use CPTs with Jetpack's Subscriptions feature, but we'll update this issue once we start working on this.

**Comment by someguynamedphil** [comment]
Please add this or allow for some hooks to make it possible if you don't want to allow it for basic users (although why you wouldn't is bizarre).

It's been 10 years - I think this should be doable.
