### ISSUE TITLE
Gutenberg: support Gallery block

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#8527]
#### Steps to reproduce the issue

1. Install the Gutenberg plugin.
2. Create a new post.
3. Create a gallery block.
4. There are no options to pick a gallery type during the gallery creation process. This seems to be a Gutenberg issue: https://github.com/WordPress/gutenberg/issues/1450
5. Once you create the gallery and publish the post, you will notice that Carousel is not triggered when clicking on the images on the front-end. That is because Gutenberg galleries use their own markup, as per https://github.com/WordPress/gutenberg/issues/2900

We would need to make sure that both Tiled Galleries and Carousel can be applied to Gutenberg galleries.

Related: 
- https://github.com/WordPress/gutenberg/issues/1704
- https://github.com/WordPress/gutenberg/issues/1728

**Comment by asm0dey** [comment]
It's still valid

**Comment by mzakariya** [comment]
Referenced as a continuing issue here:

- https://wordpress.org/support/topic/gutenberg-gallery-support/

**Comment by MichaelArestad** [comment]
I'm going to close this for now. We are proceeding by making a Jetpack tiled gallery block along with, potentially, a slideshow/carousel block.

**Comment by designsimply** [comment]
I searched and found https://github.com/Automattic/jetpack/pull/10145 is the PR for the tiled gallery block and wanted to note it here in case anyone would like to follow progress or if any testers with a dev environment would like to help test it when it's ready. 😊

**Comment by bph** [comment]
@designsimply - Thanks for surfacing this closed issue. It seems in Gutenberg 3.9 the Carousel is triggered when clicking on an image in the current Gutenberg Gallery Block, provided one selects "Attachment page" under "Link to" parameter. However, the Carousel doesn't have any next/previous navigation. http://recordit.co/41vNUeUrE5 
Should I open a new issue, or will the fixed with the linked PR ?

**Comment by jeherve** [comment]
@bph Thanks for the report! That seems like something we should fix on our end, by making sure the Carousel feature is compatible with the core Gallery block.

I opened #10246 to keep track of that.

**Comment by asm0dey** [comment]
Gutenberg 4.6.1, Wordpress 5, tiled galleries still doesn't work

**Comment by jeherve** [comment]
@asm0dey This issue is for [the Carousel feature](https://jetpack.com/support/carousel/); this was implemented in Jetpack 6.8. Tiled Galleries, however, cannot be added via a block yet. That is something we are planning for Jetpack 6.9. You can follow our progress in https://github.com/Automattic/wp-calypso/pull/28944

Until Jetpack 6.9 is released, I would recommend that you use the Classic block on your site, like so:

<img width="499" alt="screenshot 2018-12-10 at 12 07 57" src="https://user-images.githubusercontent.com/426388/49728982-72f70f80-fc74-11e8-85e0-eff5101b29ce.png">
<img width="694" alt="screenshot 2018-12-10 at 12 08 06" src="https://user-images.githubusercontent.com/426388/49728981-72f70f80-fc74-11e8-91a2-6f122b085d8f.png">
<img width="1087" alt="screenshot 2018-12-10 at 12 08 19" src="https://user-images.githubusercontent.com/426388/49728980-72f70f80-fc74-11e8-9f4b-c07f8921650d.png">
<img width="1164" alt="screenshot 2018-12-10 at 12 09 01" src="https://user-images.githubusercontent.com/426388/49728978-72f70f80-fc74-11e8-989b-b67a24093cac.png">
<img width="797" alt="screenshot 2018-12-10 at 12 09 07" src="https://user-images.githubusercontent.com/426388/49728977-725e7900-fc74-11e8-825a-41a3c8b7a773.png">

**Comment by asm0dey** [comment]
@jeherve hah, looks funny! Thanks, will use classic editor until tiled galleries will be supported :)
